# This file should contain all the record creation needed to seed the database
#  with its default values.
# The data can then be loaded with the rails db:seed command
# (or created alongside the database with db:setup).
Provincia.create(codigo: '02', nombre: 'Albacete')
Provincia.create(codigo: '03', nombre: 'Alacant/Alicante')
Provincia.create(codigo: '04', nombre: 'Almería')
Provincia.create(codigo: '01', nombre: 'Araba/Álava')
Provincia.create(codigo: '33', nombre: 'Asturias')
Provincia.create(codigo: '05', nombre: 'Ávila')
Provincia.create(codigo: '06', nombre: 'Badajoz')
Provincia.create(codigo: '07', nombre: 'Balears, Illes')
Provincia.create(codigo: '08', nombre: 'Barcelona')
Provincia.create(codigo: '48', nombre: 'Bizkaia/Vizcaya')
Provincia.create(codigo: '09', nombre: 'Burgos')
Provincia.create(codigo: '10', nombre: 'Cáceres')
Provincia.create(codigo: '11', nombre: 'Cádiz')
Provincia.create(codigo: '39', nombre: 'Cantabria')
Provincia.create(codigo: '12', nombre: 'Castelló/Castellón')
Provincia.create(codigo: '13', nombre: 'Ciudad Real')
Provincia.create(codigo: '14', nombre: 'Córdoba')
Provincia.create(codigo: '15', nombre: 'Coruña, A')
Provincia.create(codigo: '16', nombre: 'Cuenca')
Provincia.create(codigo: '20', nombre: 'Gipuzkoa/Guipúzcoa')
Provincia.create(codigo: '17', nombre: 'Girona/Gerona')
Provincia.create(codigo: '18', nombre: 'Granada')
Provincia.create(codigo: '19', nombre: 'Guadalajara')
Provincia.create(codigo: '21', nombre: 'Huelva')
Provincia.create(codigo: '22', nombre: 'Huesca')
Provincia.create(codigo: '23', nombre: 'Jaén')
Provincia.create(codigo: '24', nombre: 'León')
Provincia.create(codigo: '25', nombre: 'Lleida/Lérida')
Provincia.create(codigo: '27', nombre: 'Lugo')
Provincia.create(codigo: '28', nombre: 'Madrid')
Provincia.create(codigo: '29', nombre: 'Málaga')
Provincia.create(codigo: '30', nombre: 'Murcia')
Provincia.create(codigo: '31', nombre: 'Navarra')
Provincia.create(codigo: '32', nombre: 'Ourense/Orense')
Provincia.create(codigo: '34', nombre: 'Palencia')
Provincia.create(codigo: '35', nombre: 'Palmas, Las')
Provincia.create(codigo: '36', nombre: 'Pontevedra')
Provincia.create(codigo: '26', nombre: 'Rioja, La')
Provincia.create(codigo: '37', nombre: 'Salamanca')
Provincia.create(codigo: '38', nombre: 'Santa Cruz de Tenerife')
Provincia.create(codigo: '40', nombre: 'Segovia')
Provincia.create(codigo: '41', nombre: 'Sevilla')
Provincia.create(codigo: '42', nombre: 'Soria')
Provincia.create(codigo: '43', nombre: 'Tarragona')
Provincia.create(codigo: '44', nombre: 'Teruel')
Provincia.create(codigo: '45', nombre: 'Toledo')
Provincia.create(codigo: '46', nombre: 'València/Valencia')
Provincia.create(codigo: '47', nombre: 'Valladolid')
Provincia.create(codigo: '49', nombre: 'Zamora')
Provincia.create(codigo: '50', nombre: 'Zaragoza')
Provincia.create(codigo: '51', nombre: 'Ceuta')
Provincia.create(codigo: '52', nombre: 'Melilla')

Colegio.create(nombre: 'Colegio de Graduados Sociales de Asturias',
               direccion: 'Cervantes, 28 - 1º. F.',
               poblacion: 'Oviedo',
               codigo_postal: '33004',
               provincia_id: 5,
               cif: 'Q-3369005H',
               url: 'http://www.graduadosocialasturias.es',
               email: 'info@graduadosocialasturias.es',
               telefono: '985 277 873',
               fax: '985 234 161')

Pais.create(nombre: 'Afganistán', codigo: 'AF')
Pais.create(nombre: 'Aland', codigo: 'AX')
Pais.create(nombre: 'Albania', codigo: 'AL')
Pais.create(nombre: 'Alemania', codigo: 'DE')
Pais.create(nombre: 'Andorra', codigo: 'AD')
Pais.create(nombre: 'Angola', codigo: 'AO')
Pais.create(nombre: 'Anguila', codigo: 'AI')
Pais.create(nombre: 'Antártida', codigo: 'AQ')
Pais.create(nombre: 'Antigua y Barbuda', codigo: 'AG')
Pais.create(nombre: 'Antillas Neerlandesas', codigo: 'AN')
Pais.create(nombre: 'Arabia Saudita', codigo: 'SA')
Pais.create(nombre: 'Argelia', codigo: 'DZ')
Pais.create(nombre: 'Argentina', codigo: 'AR')
Pais.create(nombre: 'Armenia', codigo: 'AM')
Pais.create(nombre: 'Aruba', codigo: 'AW')
Pais.create(nombre: 'Australia', codigo: 'AU')
Pais.create(nombre: 'Austria', codigo: 'AT')
Pais.create(nombre: 'Azerbaiyán', codigo: 'AZ')
Pais.create(nombre: 'Bahamas', codigo: 'BS')
Pais.create(nombre: 'Bahréin', codigo: 'BH')
Pais.create(nombre: 'Bangladesh', codigo: 'BD')
Pais.create(nombre: 'Barbados', codigo: 'BB')
Pais.create(nombre: 'Bielorrusia', codigo: 'BY')
Pais.create(nombre: 'Bélgica', codigo: 'BE')
Pais.create(nombre: 'Belice', codigo: 'BZ')
Pais.create(nombre: 'Benín', codigo: 'BJ')
Pais.create(nombre: 'Bermudas', codigo: 'BM')
Pais.create(nombre: 'Bután', codigo: 'BT')
Pais.create(nombre: 'Bolivia', codigo: 'BO')
Pais.create(nombre: 'Bosnia y Herzegovina', codigo: 'BA')
Pais.create(nombre: 'Botsuana', codigo: 'BW')
Pais.create(nombre: 'Isla Bouvet', codigo: 'BV')
Pais.create(nombre: 'Brasil', codigo: 'BR')
Pais.create(nombre: 'Brunéi', codigo: 'BN')
Pais.create(nombre: 'Bulgaria', codigo: 'BG')
Pais.create(nombre: 'Burkina Faso', codigo: 'BF')
Pais.create(nombre: 'Burundi', codigo: 'BI')
Pais.create(nombre: 'Cabo Verde', codigo: 'CV')
Pais.create(nombre: 'Islas Caimán', codigo: 'KY')
Pais.create(nombre: 'Camboya', codigo: 'KH')
Pais.create(nombre: 'Camerún', codigo: 'CM')
Pais.create(nombre: 'Canadá', codigo: 'CA')
Pais.create(nombre: 'República Centroaficana', codigo: 'CF')
Pais.create(nombre: 'Chad', codigo: 'TD')
Pais.create(nombre: 'República Checa', codigo: 'CZ')
Pais.create(nombre: 'Chile', codigo: 'CL')
Pais.create(nombre: 'China', codigo: 'CN')
Pais.create(nombre: 'Chipre', codigo: 'CY')
Pais.create(nombre: 'Islas Cocos', codigo: 'CC')
Pais.create(nombre: 'Colombia', codigo: 'CO')
Pais.create(nombre: 'Comoras', codigo: 'KM')
Pais.create(nombre: 'República del Congo', codigo: 'CG')
Pais.create(nombre: 'República Democrática del Congo', codigo: 'CD')
Pais.create(nombre: 'Islas Cook', codigo: 'CK')
Pais.create(nombre: 'Corea del Norte', codigo: 'KP')
Pais.create(nombre: 'Corea del Sur', codigo: 'KR')
Pais.create(nombre: 'Costa de Marfil', codigo: 'CI')
Pais.create(nombre: 'Costa Rica', codigo: 'CR')
Pais.create(nombre: 'Croacia', codigo: 'HR')
Pais.create(nombre: 'Cuba', codigo: 'CU')
Pais.create(nombre: 'Dinamarca', codigo: 'DK')
Pais.create(nombre: 'Dominica', codigo: 'DM')
Pais.create(nombre: 'República Dominicana', codigo: 'DO')
Pais.create(nombre: 'Ecuador', codigo: 'EC')
Pais.create(nombre: 'Egipto', codigo: 'EG')
Pais.create(nombre: 'El Salvador', codigo: 'SV')
Pais.create(nombre: 'Emiratos Árabes Unidos', codigo: 'AE')
Pais.create(nombre: 'Eritrea', codigo: 'ER')
Pais.create(nombre: 'Eslovaquia', codigo: 'SK')
Pais.create(nombre: 'Eslovenia', codigo: 'SI')
Pais.create(nombre: 'España', codigo: 'ES')
Pais.create(nombre: 'Estados Unidos', codigo: 'US')
Pais.create(nombre: 'Islas ultramarinas de Estados Unidos', codigo: 'UM')
Pais.create(nombre: 'España (Ceuta y Melilla)', codigo: 'EA')
Pais.create(nombre: 'Estonia', codigo: 'EE')
Pais.create(nombre: 'Etiopía', codigo: 'ET')
Pais.create(nombre: 'Islas Feroe', codigo: 'FO')
Pais.create(nombre: 'Filipinas', codigo: 'PH')
Pais.create(nombre: 'Finlandia', codigo: 'FI')
Pais.create(nombre: 'Fiyi', codigo: 'FJ')
Pais.create(nombre: 'Francia', codigo: 'FR')
Pais.create(nombre: 'Gabón', codigo: 'GA')
Pais.create(nombre: 'Gambia', codigo: 'GM')
Pais.create(nombre: 'Georgia', codigo: 'GE')
Pais.create(nombre: 'Islas Georgias del Sur y Sandwich del Sur', codigo: 'GS')
Pais.create(nombre: 'Ghana', codigo: 'GH')
Pais.create(nombre: 'Gibraltar', codigo: 'GI')
Pais.create(nombre: 'Granada', codigo: 'GD')
Pais.create(nombre: 'Grecia', codigo: 'GR')
Pais.create(nombre: 'Groenlandia', codigo: 'GL')
Pais.create(nombre: 'Guadalupe', codigo: 'GP')
Pais.create(nombre: 'Guam', codigo: 'GU')
Pais.create(nombre: 'Guatemala', codigo: 'GT')
Pais.create(nombre: 'Guayana Francesa', codigo: 'GF')
Pais.create(nombre: 'Guernsey', codigo: 'GG')
Pais.create(nombre: 'Guinea', codigo: 'GN')
Pais.create(nombre: 'Guinea Ecuatorial', codigo: 'GQ')
Pais.create(nombre: 'Guinea-Bissau', codigo: 'GW')
Pais.create(nombre: 'Guyana', codigo: 'GY')
Pais.create(nombre: 'Haití', codigo: 'HT')
Pais.create(nombre: 'Islas Heard y McDonald', codigo: 'HM')
Pais.create(nombre: 'Honduras', codigo: 'HN')
Pais.create(nombre: 'Hong Kong', codigo: 'HK')
Pais.create(nombre: 'Hungría', codigo: 'HU')
Pais.create(nombre: 'India', codigo: 'IN')
Pais.create(nombre: 'Indonesia', codigo: 'ID')
Pais.create(nombre: 'Irán', codigo: 'IR')
Pais.create(nombre: 'Iraq', codigo: 'IQ')
Pais.create(nombre: 'Irlanda', codigo: 'IE')
Pais.create(nombre: 'Islandia', codigo: 'IS')
Pais.create(nombre: 'Israel', codigo: 'IL')
Pais.create(nombre: 'Italia', codigo: 'IT')
Pais.create(nombre: 'Jamaica', codigo: 'JM')
Pais.create(nombre: 'Japón', codigo: 'JP')
Pais.create(nombre: 'Jersey', codigo: 'JE')
Pais.create(nombre: 'Jordania', codigo: 'JO')
Pais.create(nombre: 'Kazajistán', codigo: 'KZ')
Pais.create(nombre: 'Kenia', codigo: 'KE')
Pais.create(nombre: 'Kirguistán', codigo: 'KG')
Pais.create(nombre: 'Kiribati', codigo: 'KI')
Pais.create(nombre: 'Kuwait', codigo: 'KW')
Pais.create(nombre: 'Laos', codigo: 'LA')
Pais.create(nombre: 'Lesoto', codigo: 'LS')
Pais.create(nombre: 'Letonia', codigo: 'LV')
Pais.create(nombre: 'Líbano', codigo: 'LB')
Pais.create(nombre: 'Liberia', codigo: 'LR')
Pais.create(nombre: 'Libia', codigo: 'LY')
Pais.create(nombre: 'Liechtenstein', codigo: 'LI')
Pais.create(nombre: 'Lituania', codigo: 'LT')
Pais.create(nombre: 'Luxemburgo', codigo: 'LU')
Pais.create(nombre: 'Macao', codigo: 'MO')
Pais.create(nombre: 'ARY Macedonia', codigo: 'MK')
Pais.create(nombre: 'Madagascar', codigo: 'MG')
Pais.create(nombre: 'Malasia', codigo: 'MY')
Pais.create(nombre: 'Malawi', codigo: 'MW')
Pais.create(nombre: 'Maldivas', codigo: 'MV')
Pais.create(nombre: 'Malí', codigo: 'ML')
Pais.create(nombre: 'Malta', codigo: 'MT')
Pais.create(nombre: 'Islas Malvinas', codigo: 'FK')
Pais.create(nombre: 'Isla de Man', codigo: 'IM')
Pais.create(nombre: 'Islas Marianas del Norte', codigo: 'MP')
Pais.create(nombre: 'Marruecos', codigo: 'MA')
Pais.create(nombre: 'Islas Marshall', codigo: 'MH')
Pais.create(nombre: 'Martinica', codigo: 'MQ')
Pais.create(nombre: 'Mauricio', codigo: 'MU')
Pais.create(nombre: 'Mauritania', codigo: 'MR')
Pais.create(nombre: 'Mayotte', codigo: 'YT')
Pais.create(nombre: 'México', codigo: 'MX')
Pais.create(nombre: 'Micronesia', codigo: 'FM')
Pais.create(nombre: 'Moldavia', codigo: 'MD')
Pais.create(nombre: 'Mónaco', codigo: 'MC')
Pais.create(nombre: 'Mongolia', codigo: 'MN')
Pais.create(nombre: 'Montenegro', codigo: 'ME')
Pais.create(nombre: 'Montserrat', codigo: 'MS')
Pais.create(nombre: 'Mozambique', codigo: 'MZ')
Pais.create(nombre: 'Myanmar', codigo: 'MM')
Pais.create(nombre: 'Namibia', codigo: 'NA')
Pais.create(nombre: 'Nauru', codigo: 'NR')
Pais.create(nombre: 'Isla de Navidad', codigo: 'CX')
Pais.create(nombre: 'Nepal', codigo: 'NP')
Pais.create(nombre: 'Nicaragua', codigo: 'NI')
Pais.create(nombre: 'Níger', codigo: 'NE')
Pais.create(nombre: 'Nigeria', codigo: 'NG')
Pais.create(nombre: 'Niue', codigo: 'NU')
Pais.create(nombre: 'Norfolk', codigo: 'NF')
Pais.create(nombre: 'Noruega', codigo: 'NO')
Pais.create(nombre: 'Nueva Caledonia', codigo: 'NC')
Pais.create(nombre: 'Nueva Zelanda', codigo: 'NZ')
Pais.create(nombre: 'Omán', codigo: 'OM')
Pais.create(nombre: 'Países Bajos', codigo: 'NL')
Pais.create(nombre: 'Pakistán', codigo: 'PK')
Pais.create(nombre: 'Palaos', codigo: 'PW')
Pais.create(nombre: 'Palestina (ANP)', codigo: 'PS')
Pais.create(nombre: 'Panamá', codigo: 'PA')
Pais.create(nombre: 'Papúa Nueva Guinea', codigo: 'PG')
Pais.create(nombre: 'Paraguay', codigo: 'PY')
Pais.create(nombre: 'Perú', codigo: 'PE')
Pais.create(nombre: 'Islas Pitcairn', codigo: 'PN')
Pais.create(nombre: 'Polinesia Francesa', codigo: 'PF')
Pais.create(nombre: 'Polonia', codigo: 'PL')
Pais.create(nombre: 'Portugal', codigo: 'PT')
Pais.create(nombre: 'Puerto Rico', codigo: 'PR')
Pais.create(nombre: 'Qatar', codigo: 'QA')
Pais.create(nombre: 'Reino Unido', codigo: 'GB')
Pais.create(nombre: 'Reunión', codigo: 'RE')
Pais.create(nombre: 'Ruanda', codigo: 'RW')
Pais.create(nombre: 'Rumania', codigo: 'RO')
Pais.create(nombre: 'Rusia', codigo: 'RU')
Pais.create(nombre: 'Sahara Occidental', codigo: 'EH')
Pais.create(nombre: 'Islas Salomón', codigo: 'SB')
Pais.create(nombre: 'Samoa', codigo: 'WS')
Pais.create(nombre: 'Samoa Americana', codigo: 'AS')
Pais.create(nombre: 'San Cristobal y Nieves', codigo: 'KN')
Pais.create(nombre: 'San Marino', codigo: 'SM')
Pais.create(nombre: 'San Pedro y Miquelón', codigo: 'PM')
Pais.create(nombre: 'San Vicente y las Granadinas', codigo: 'VC')
Pais.create(nombre: 'Santa Helena', codigo: 'SH')
Pais.create(nombre: 'Santa Lucía', codigo: 'LC')
Pais.create(nombre: 'Santo Tomé y Príncipe', codigo: 'ST')
Pais.create(nombre: 'Senegal', codigo: 'SN')
Pais.create(nombre: 'Serbia', codigo: 'RS')
Pais.create(nombre: 'Seychelles', codigo: 'SC')
Pais.create(nombre: 'Sierra Leona', codigo: 'SL')
Pais.create(nombre: 'Singapur', codigo: 'SG')
Pais.create(nombre: 'Siria', codigo: 'SY')
Pais.create(nombre: 'Somalia', codigo: 'SO')
Pais.create(nombre: 'Sri Lanka', codigo: 'RK')
Pais.create(nombre: 'Suazilandia', codigo: 'SZ')
Pais.create(nombre: 'Sudáfrica', codigo: 'ZA')
Pais.create(nombre: 'Sudán', codigo: 'SD')
Pais.create(nombre: 'Suecia', codigo: 'SE')
Pais.create(nombre: 'Suiza', codigo: 'CH')
Pais.create(nombre: 'Surinam', codigo: 'SR')
Pais.create(nombre: 'Svalbard y Jan Mayen', codigo: 'SJ')
Pais.create(nombre: 'Tailandia', codigo: 'TH')
Pais.create(nombre: 'Taiwán', codigo: 'TW')
Pais.create(nombre: 'Tanzania', codigo: 'TZ')
Pais.create(nombre: 'Tayikistán', codigo: 'TJ')
Pais.create(nombre: 'Territorio Británico del Océano Índico', codigo: 'IO')
Pais.create(nombre: 'Territorios Australes Franceses', codigo: 'TF')
Pais.create(nombre: 'Timor Oriental', codigo: 'TL')
Pais.create(nombre: 'Togo', codigo: 'TG')
Pais.create(nombre: 'Tokelau', codigo: 'TK')
Pais.create(nombre: 'Tonga', codigo: 'TO')
Pais.create(nombre: 'Trinidad y Tobago', codigo: 'TT')
Pais.create(nombre: 'Túnez', codigo: 'TN')
Pais.create(nombre: 'Islas Turcas y Caicos', codigo: 'TC')
Pais.create(nombre: 'Turkmenistán', codigo: 'TM')
Pais.create(nombre: 'Turquía', codigo: 'TR')
Pais.create(nombre: 'Tuvalu', codigo: 'TV')
Pais.create(nombre: 'Ucrania', codigo: 'UA')
Pais.create(nombre: 'Uganda', codigo: 'UG')
Pais.create(nombre: 'Uruguay', codigo: 'UY')
Pais.create(nombre: 'Uzbekistán', codigo: 'UZ')
Pais.create(nombre: 'Vanuatu', codigo: 'VU')
Pais.create(nombre: 'Ciudad del Vaticano', codigo: 'VA')
Pais.create(nombre: 'Venezuela', codigo: 'VE')
Pais.create(nombre: 'Vietnam', codigo: 'VN')
Pais.create(nombre: 'Islas Vírgenes Británicas', codigo: 'VG')
Pais.create(nombre: 'Islas Vírgenes Estadounidenses', codigo: 'VI')
Pais.create(nombre: 'Wallis y Futuna', codigo: 'WF')
Pais.create(nombre: 'Yemen', codigo: 'YE')
Pais.create(nombre: 'Yibuti', codigo: 'DJ')
Pais.create(nombre: 'Zambia', codigo: 'ZM')
Pais.create(nombre: 'Zimbabue', codigo: 'ZW')

Period.create(nombre: 'Mensual', multiplicador: 1)
Period.create(nombre: 'Bimestral', multiplicador: 2)
Period.create(nombre: 'Trimestral', multiplicador: 3)
Period.create(nombre: 'Semestral', multiplicador: 6)

Cargo.create(nombre: 'Interventor', codigo: '1')
Cargo.create(nombre: 'Presidente', codigo: '2')
Cargo.create(nombre: 'Presidente de Honor', codigo: '3')
Cargo.create(nombre: 'Secretario', codigo: '4')
Cargo.create(nombre: 'Tesorero', codigo: '5')
Cargo.create(nombre: 'Vicepresidente 1º', codigo: '6')
Cargo.create(nombre: 'Vicepresidente 2º', codigo: '7')
Cargo.create(nombre: 'Vicepresidente 3º', codigo: '8')
Cargo.create(nombre: 'Vicesecretario', codigo: '9')
Cargo.create(nombre: 'Vocal Ejercientes', codigo: '10')
Cargo.create(nombre: 'Vocal No Ejercientes', codigo: '11')

RegimenColegiado.create(literal: 'Ejerciente libre', period_id: Period.first.id)
RegimenColegiado.create(literal: 'Ejerciente por cuenta ajena', period_id: Period.first.id)
RegimenColegiado.create(literal: 'Emérito', period_id: Period.first.id)
RegimenColegiado.create(literal: 'No jerciente', period_id: Period.first.id)
RegimenColegiado.create(literal: 'Precolegiado', period_id: Period.first.id)

CausaBaja.create(nombre: 'Baja Voluntaria', codigo: '1')
CausaBaja.create(nombre: 'Cambio de Cargo', codigo: '2')
CausaBaja.create(nombre: 'Cese', codigo: '3')
CausaBaja.create(nombre: 'Dimisión', codigo: '4')
CausaBaja.create(nombre: 'Fallecimiento', codigo: '5')
CausaBaja.create(nombre: 'Fin de Mandato', codigo: '6')
CausaBaja.create(nombre: 'Moción de Censura', codigo: '7')

Titulacion.create(nombre: 'Escuela Social')
Titulacion.create(nombre: 'Graduado Social Diplomado')
Titulacion.create(nombre: 'Diplomado en Relaciones Laborales')
Titulacion.create(nombre: 'Grado en Relaciones Laborales y Recursos Humanos')

TipoMovimiento.create(literal: 'Alta', codigo: 'A')
TipoMovimiento.create(literal: 'Baja', codigo: 'B')
TipoMovimiento.create(literal: 'Modificación', codigo: 'M')

# Initialize first account:
User.create! do |u|
  u.email     = 'test@cgs.es'
  u.username  = 'admin_test'
  u.password  = 'password'
  u.password_confirmation = 'password'
  u.superadmin_rol = true
end

Documento.create(nombre: 'Cambio de estado', codigo: 'cambio_estado', plantilla: 'plantilla_colegiado', documento_personal: true)
Documento.create(nombre: 'Cambio de régimen', codigo: 'cambio_regimen', plantilla: 'plantilla_colegiado', documento_personal: true)
Documento.create(nombre: 'Certificado de colegiación', codigo: 'certificado_colegiacion', plantilla: 'plantilla_colegiado', documento_personal: true)
Documento.create(nombre: 'Certificado de cuotas', codigo: 'certificado_cuotas', plantilla: 'plantilla_colegiado', documento_personal: true)
Documento.create(nombre: 'Recibo Manual', codigo: 'recibo', plantilla: 'plantilla_recibo', documento_personal: true)
Documento.create(nombre: 'Convocatoria de Junta de Gobierno', codigo: 'junta_gobierno', plantilla: 'plantilla_junta', documento_personal: false)
Documento.create(nombre: 'Convocatoria de Junta General Ordinaria', codigo: 'junta_general', plantilla: 'plantilla_junta', documento_personal: false)
Documento.create(nombre: 'Modelo 13', codigo: 'modelo_13', plantilla: 'plantilla_modelo_13', documento_personal: true)
Documento.create(nombre: 'Domiciliación Bancaria', codigo: 'domiciliacion_bancaria', plantilla: 'plantilla_domiciliacion', documento_personal: true)
Documento.create(nombre: 'Etiquetas', codigo: 'etiqueta', plantilla: 'plantilla_etiqueta', documento_personal: false)
Documento.create(nombre: 'Listado de Colegiados', codigo: 'listado', plantilla: 'plantilla_listado', documento_personal: false)
